spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
    password: tiwhdrl12
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
